import { Artist, ProjectFolder } from './types';

export const CURATED_TAGS = [
  'Illustration',
  'Digital Art',
  'Concept Art',
  'Character Design',
  '3D Modeling',
  'Animation',
  'Photography',
  'Sketch',
  'Adobe Photoshop',
  'Illustrator',
  'Blender',
  'Krita',
  'Procreate',
  'Paint Tool Sai',
  'Ink',
  'Marker',
  'Watercolor',
  'Gouache',
  'Oil Paint',
  'Acrylic Paint',
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    name: 'Elara Vance',
    username: 'elarav',
    avatar: 'https://picsum.photos/seed/elara/200/200',
    bio: 'Concept artist and illustrator specializing in dark fantasy and surrealism.',
    bannerUrl: 'https://picsum.photos/seed/elara-banner/1200/400',
    tags: ['Digital Art', 'Concept Art', 'Dark Fantasy'],
    hasManicule: true,
  },
  {
    id: 'artist-2',
    name: 'Marcus Thorne',
    username: 'mthorne',
    avatar: 'https://picsum.photos/seed/marcus/200/200',
    bio: '3D artist focused on architectural visualization and environmental storytelling.',
    bannerUrl: 'https://picsum.photos/seed/marcus-banner/1200/400',
    tags: ['3D Modeling', 'Blender', 'Architecture'],
  },
  {
    id: 'artist-3',
    name: 'Sora Kim',
    username: 'sorakim',
    avatar: 'https://picsum.photos/seed/sora/200/200',
    bio: 'Digital painter and character designer inspired by nature and mythology.',
    bannerUrl: 'https://picsum.photos/seed/sora-banner/1200/400',
    tags: ['Digital Art', 'Character Design', 'Krita'],
    hasManicule: true,
  },
  {
    id: 'artist-4',
    name: 'Julian Rossi',
    username: 'jrossi',
    avatar: 'https://picsum.photos/seed/julian/200/200',
    bio: 'Traditional oil painter exploring the intersection of classical techniques and modern subjects.',
    bannerUrl: 'https://picsum.photos/seed/julian-banner/1200/400',
    tags: ['Oil Paint', 'Traditional', 'Portrait'],
  },
  {
    id: 'artist-5',
    name: 'Aria Chen',
    username: 'ariachen',
    avatar: 'https://picsum.photos/seed/aria/200/200',
    bio: 'Motion designer and animator creating fluid, abstract visual experiences.',
    bannerUrl: 'https://picsum.photos/seed/aria-banner/1200/400',
    tags: ['Animation', 'Motion Design', 'After Effects'],
    hasManicule: true,
  },
  {
    id: 'artist-6',
    name: 'Leo Vance',
    username: 'leov',
    avatar: 'https://picsum.photos/seed/leo/200/200',
    bio: 'Street photographer capturing the raw energy of urban life.',
    bannerUrl: 'https://picsum.photos/seed/leo-banner/1200/400',
    tags: ['Photography', 'Street', 'Black & White'],
  },
];

export const MOCK_PROJECTS: ProjectFolder[] = [
  {
    id: 'p1',
    title: 'The Obsidian Spire',
    description: 'A series of concept sketches for a dark fantasy environment.',
    authorUid: 'artist-1',
    authorName: 'Elara Vance',
    authorPhoto: 'https://picsum.photos/seed/elara/200/200',
    imageUrl: 'https://picsum.photos/seed/spire1/800/600',
    category: 'Concept Art',
    tags: ['Concept Art', 'Digital Art', 'Ink'],
    likesCount: 124,
    createdAt: { seconds: 1710900000, nanoseconds: 0 },
    hasManicule: true,
  },
  {
    id: 'p2',
    title: 'Neon Dreams',
    description: 'Exploring cyberpunk aesthetics through 3D renders.',
    authorUid: 'artist-2',
    authorName: 'Marcus Thorne',
    authorPhoto: 'https://picsum.photos/seed/marcus/200/200',
    imageUrl: 'https://picsum.photos/seed/neon1/800/600',
    category: '3D Modeling',
    tags: ['3D Modeling', 'Blender', 'Cyberpunk'],
    likesCount: 89,
    createdAt: { seconds: 1711332000, nanoseconds: 0 },
  },
  {
    id: 'p3',
    title: 'Anatomical Studies',
    description: 'Traditional ink and marker sketches of human anatomy.',
    authorUid: 'artist-1',
    authorName: 'Elara Vance',
    authorPhoto: 'https://picsum.photos/seed/elara/200/200',
    imageUrl: 'https://picsum.photos/seed/anatomy1/800/600',
    category: 'Sketch',
    tags: ['Ink', 'Marker', 'Sketch'],
    likesCount: 256,
    createdAt: { seconds: 1711591200, nanoseconds: 0 },
    hasManicule: true,
  },
];
